# Numpy

In [337]:
import numpy as np

### Basic initialization

In [338]:
arr = np.array([1, 2, 3, 4], dtype=np.int8)
arr


array([1, 2, 3, 4], dtype=int8)

In [339]:
b= np.arange(2,9)
b

array([2, 3, 4, 5, 6, 7, 8])

In [340]:
b[[0,3,-1]]

array([2, 5, 8])

In [341]:
z = np.zeros((2,3))
o = np.ones(5)
print(o)
print("z:",z)

[1. 1. 1. 1. 1.]
z: [[0. 0. 0.]
 [0. 0. 0.]]


### Matrices

In [342]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [343]:
A[0,2]

3

In [344]:
A[0][2]

3

In [345]:
A.dtype

dtype('int32')

In [346]:
A.shape

(3, 3)

In [347]:
A.ndim

2

In [348]:
A.size

9

### Statistics

In [349]:
arr

array([1, 2, 3, 4], dtype=int8)

In [350]:
arr.mean()

2.5

In [351]:
arr.sum()

10

In [352]:
arr.std()

1.118033988749895

In [353]:
arr.var()

1.25

### Operations

In [354]:
arr

array([1, 2, 3, 4], dtype=int8)

In [355]:
arr +=5
arr

array([6, 7, 8, 9], dtype=int8)

In [356]:
b

array([2, 3, 4, 5, 6, 7, 8])

In [357]:
arr*b[:4]

array([12, 21, 32, 45])

##### boolean operations

In [358]:
arr %2 == 0

array([ True, False,  True, False])

In [359]:
arr[arr%2==0]

array([6, 8], dtype=int8)